### ISSUE TITLE
Accessing ShopifyQL?

### ISSUE THREAD

**Issue by bakura10** [Shopify/polaris#149] opened 2017-07-25 14:54 UTC
# Issue summary

Hi,

Our next app will make use of Shopify QL. However I realize that there is no way in Polaris to access the Shopify QL object (ShopifyApp.ShopifyAnalytics).

Could you please add a note in the documentation on how the app can fetch analytics?

Thanks!

**Comment by ry5n** [comment] 2017-08-01 15:38
Hey! [This page](https://help.shopify.com/api/sdks/shopify-apps/embedded-app-sdk) might make it seem like you need to choose between Polaris and the EASDK (let me know if you got that impression). That’s not the case though. You can (and should 👍 ) use Polaris and the [Embedded App SDK](https://help.shopify.com/api/sdks/shopify-apps/embedded-app-sdk/getting-started) together. 

In fact, you need to use to build your app using the EASDK in order to access Shopify QL. Polaris doesn’t have any components that abstract over the Shopify QL API, but [you can still use it directly](https://help.shopify.com/api/reference/shopify-ql).

**Comment by bakura10** [comment] 2017-08-01 15:41
Hi !

I'd love to do that but... what are the endpoints? The doc explicitly says that we need to use Embedded App SDK.

**Comment by ry5n** [comment] 2017-08-01 17:13
You’re right, there are no endpoints listed. I’m going to dig into this a bit more.

**Comment by cepix** [comment] 2017-09-06 22:09
Any new information  @bakura10 @ry5n? I was looking for the same

**Comment by bakura10** [comment] 2017-09-07 07:50
Nope, I'm still waiting for this one :(.

**Comment by ry5n** [comment] 2017-09-07 22:29
Sorry for the delay on this.

With the EmbeddedApp component, we expose some of the underlying EASDK functionality via React’s context [as described here](https://github.com/Shopify/polaris/blob/master/documentation/Embedded%20apps.md#access-to-further-easdk-apis). The methods provided are `showFlashNotice()`, `pushState()`, `redirect()`, `startLoading()` and `stopLoading`.

It turns out the original EASDK offers an [Analytics API](https://help.shopify.com/api/tutorials/analytics-api#example-request). To make [ShopifyQL queries](https://help.shopify.com/api/reference/shopify-ql), you’d use that API rather than making HTTP requests to endpoints.

It doesn’t look like an equivalent is current exposed by the EmbeddedApp component. I still need to confirm that. I’ll also let you know if there’s a workaround and what plans exist to make it available in Polaris.

**Comment by cepix** [comment] 2017-09-08 12:49
I will share news as soon as I got some piece of working code....thanks @ry5n !

**Comment by ry5n** [comment] 2017-09-20 18:37
I can confirm that currently using the React components there isn’t a direct way to access the regular EASDK (and make ShopifyQL calls) from the embedded React components. I’ve logged this internally and we’re working on addressing these limitations.

**Comment by ry5n** [comment] 2018-06-07 02:35
Unfortunately we haven’t been able to put this at the top of our priority list, but we treat all feature requests as part of our backlog.

I’ll close this issue for now, but **we encourage everyone who wants this feature to add a 👍** to the original issue report. We’ll take your collective interest into account when we look at what to work on next.

💜

**Closed by ry5n** 2018-06-07 02:35 UTC
Labels: EASDK
