### ISSUE TITLE
Resource List does not show a header

### ISSUE THREAD

**Issue by ChristianLopezGonzalez** [Shopify/polaris#427] opened 2018-09-14 10:37 UTC
# Issue summary
The promotedBulkActions property <ResourceList> not work.

<Page
                singleColumn
                breadcrumbs={this.props.breadcrumbs}
                title={this.props.title}
            >

                <Layout>
                    <Layout.Section>
                        <Card>
                            <ResourceList
                                resourceName={this.props.resourceName}
                                items={this.props.packagins}
                                renderItem={this.renderResourceItem}
                                selectedItems={this.props.selectedPackagins}
                                onSelectionChange={this.props.handleOnSelectionChange}
                                promotedBulkActions={[
                                    {
                                        content: 'Remove packagings',
                                        onAction: this.props.handleOnBulkDelete
                                    },
                                ]}
                                loading={true}
                            />
                        </Card>
                    </Layout.Section>
                </Layout>
            </Page>

## Expected behavior
Header with button for bulk actions, works fine at Polaris 2.8.0
![issue_2018-09-14 12_35_44-window](https://user-images.githubusercontent.com/10656934/45545527-d5c63f80-b81a-11e8-9770-f3257005f046.png)

## Actual behavior
It does not show a header

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: ^2.9.0
- Browser: Firefox 62 (x64)
- Operating System: W10

**Comment by dfmcphee** [comment] 2018-09-18 15:21
Hey @ChristianLopezGonzalez. Thanks for filing an issue. I am trying to recreate this, but not seeing the same problem. Can you try removing the `loading` prop? Are you seeing the same issue without it?

**Comment by ChristianLopezGonzalez** [comment] 2018-09-18 16:40
@dfmcphee i tried to remove the loading prop and return only the component. You're right i have the same issue.

       return (
            <ResourceList
                resourceName={{
                    singular: 'Singular',
                    plural: 'Plural'
                }}
                items={this.props.addresses}
                renderItem={(item) => {
                    const {id, alias} = item;
                    return (
                        <ResourceList.Item id={id}>
                            {alias}
                        </ResourceList.Item>
                    );
                }}
                selectedItems={[]}
                promotedBulkActions={[
                    { content: 'Action' }
                ]}
                bulkActions={[
                    { content: 'Action' },
                    { content: 'Action' },
                    { content: 'Action' },
                ]}
            />
        )

My assets file: 
`https://sdks.shopifycdn.com/polaris/2.9.0/polaris.min.css`

My imports: 
```
import React, {Component} from 'react';
import {bindActionCreators} from 'redux';
import {connect} from 'react-redux';
import {createStructuredSelector} from 'reselect';
import {ResourceList} from '@shopify/polaris';
```

**2.0.9 result:**
![2018-09-18 18_30_11-window](https://user-images.githubusercontent.com/10656934/45702327-d986f880-bb71-11e8-8f35-33609a45beb6.png)
 
**2.0.8 result:**
![2018-09-18 18_35_51-window](https://user-images.githubusercontent.com/10656934/45702391-089d6a00-bb72-11e8-8c5f-9dc5488466b9.png)


¿Any idea?

**Comment by mbaumbach** [comment] 2018-09-19 18:09
I also came across this and came up with a reproducible use case. Essentially what it comes down to is that if the items property is an empty array when the `ResourceList` control is mounted, the `listNode` state value isn't set because it's expecting the `listRef` reference to be available on `componentDidMount`. If the listNode is falsey, it doesn't create the header ever.

Here's the reproducible case, which all I did was use a setTimeout in componentDidMount to delay when the items arrive and the header won't show up: https://codesandbox.io/s/jjwmkolklw

**Comment by ChristianLopezGonzalez** [comment] 2018-09-20 08:04
Thanks @mbaumbach ! you're right ✌️.

**Comment by mbaumbach** [comment] 2018-11-08 16:29
@ChristianLopezGonzalez @dfmcphee This appears to be fixed in @shopify/polaris@next (3.0.0.rc7). Can be seen working in this new sandbox: https://codesandbox.io/s/p5jjq4pjnj

**Comment by tmlayton** [comment] 2018-11-08 18:00
It looks like this was fixed by c6d2c35a9d7329017984a90b9607add604d9d8cd

**Comment by MrNghia123** [comment] 2019-12-24 07:55
Problem seems to be re-appear from v4.0.0

**Comment by djaho** [comment] 2020-02-11 17:34
Yes, the issue is definitely present in v4.13.1.
I have personally downgraded to v3.10.0 so the header shows correctly.

**Comment by MrNghia123** [comment] 2020-04-17 04:52
v4.16.0 and still the same problem.

**Comment by DanPete** [comment] 2020-05-18 15:59
Solved this issue for myself by adding the internationalization to the AppProvider

`import AppProvider from '@shopify/polaris';
import translations from '@shopify/polaris/locales/en.json';
`
and on my AppProvider

`<AppProvider i18n={translations}>`

It also 

Using v4.22.0

**Comment by sam-cnet** [comment] 2020-10-24 20:51
@DanPete You're amazing and the solution works for @shopify/polaris - 4.27.0

**Comment by prabureddy** [comment] 2021-01-05 19:12
> Solved this issue for myself by adding the internationalization to the AppProvider
> 
> `import translations from '@shopify/polaris/locales/en.json';`
> and on my AppProvider
> 
> `<AppProvider i18n={translations}>`
> 
> It also
> 
> Using v4.22.0

Thanks, It worked...

**Comment by nodeit** [comment] 2022-05-15 23:16
Just wanted to chime in and say this is still an issue in v9.7.0. It is fixed by adding translations to the provider but I don't see this documented anywhere.

**Closed** 2023-04-14 03:32 UTC
Labels: Bug, no-issue-activity
