### ISSUE TITLE
Field misalignment with combinations of Formlayout and Card

### ISSUE THREAD

**Issue by BarryCarlyon** [Shopify/polaris#319] opened 2018-05-10 11:22 UTC
Field misalignment in nested items.

This could be a usage error my behalf but the layout/nesting makes sense to me.

This alignment issue existed in pre v2 also

## Expected behavior

Fields to line up nicely

## Actual behavior

Fields don't line up nicely

![image](https://user-images.githubusercontent.com/20999/39867394-9aa6a61a-544c-11e8-9c56-edd9ee6befd4.png)

Issues also exists without the `<Card />`

![image](https://user-images.githubusercontent.com/20999/39867560-6ee294fc-544d-11e8-8986-385f6d1faeef.png)

Doing something "weird" like wrapping groups of fields in groups, "fixes" alignment, but then you get wasted left margin:

![image](https://user-images.githubusercontent.com/20999/39867685-0249cff8-544e-11e8-805b-c41b11390f9a.png)

## Steps to reproduce the problem

Screenshots 1/2

    render() {
        return (
            <FormLayout>
                <Form onSubmit={this.handleSubmit}>
                    <Card
                        title="Creating a new Supplier"
                        sectioned
                    >
                        <TextField
                            label="Supplier Name"
                            value={this.state.name}
                            id="name"
                            name="name"
                            onChange={this.handleChange}
                        />

                        <TextField
                            label="Notes"
                            value={this.state.notes}
                            id="notes"
                            name="notes"
                            onChange={this.handleChange}
                            multiline
                        />

                        <FormLayout.Group>
                            <TextField
                                label="Carriage"
                                value={this.state.carriage}
                                id="carriage"
                                name="carriage"
                                onChange={this.handleChange}
                                type="number"
                                prefix="£"
                            />

                            <TextField
                                label="Lead Time"
                                value={this.state.lead}
                                id="lead"
                                name="lead"
                                onChange={this.handleChange}
                                type="number"
                                suffix="Days"
                            />
                        </FormLayout.Group>
                    </Card>
                </Form>
            </FormLayout>
        )
    }

Screenshot the third:

    render() {
        return (
            <Form onSubmit={this.handleSubmit}>
                <FormLayout>
                    <FormLayout.Group>
                    <TextField
                        label="Supplier Name"
                        value={this.state.name}
                        id="name"
                        name="name"
                        onChange={this.handleChange}
                    />
                    </FormLayout.Group>
                    <FormLayout.Group>

                    <TextField
                        label="Notes"
                        value={this.state.notes}
                        id="notes"
                        name="notes"
                        onChange={this.handleChange}
                        multiline
                    />
                    </FormLayout.Group>
                </FormLayout>
                <FormLayout>
                    <FormLayout.Group>
                        <TextField
                            label="Carriage"
                            value={this.state.carriage}
                            id="carriage"
                            name="carriage"
                            onChange={this.handleChange}
                            type="number"
                            prefix="£"
                        />

                        <TextField
                            label="Lead Time"
                            value={this.state.lead}
                            id="lead"
                            name="lead"
                            onChange={this.handleChange}
                            type="number"
                            suffix="Days"
                        />
                    </FormLayout.Group>
                </FormLayout>
            </Form>
        )
    }

## Specifications

- Polaris version: 2.0.0
- React version: 16.3.2
- Browser: Chrome
- Device: Desktop
- Operating System: Mac OSX

**Comment by mbaumbach** [comment] 2018-05-10 13:51
I think, generally, you want the `FormLayout` to more directly wrap your form components and not wrap your `Card`. The `FormLayout.Group` is also typically just used to control whether you want components on the same line. Does this layout work better for you?

```
render() {
  return (
    <Card
      title="Creating a new Supplier"
      sectioned
      >
      <Form onSubmit={this.handleSubmit}>
          <FormLayout>
            <TextField
                label="Supplier Name"
                value={this.state.name}
                id="name"
                name="name"
                onChange={this.handleChange}
            />
            <TextField
                label="Notes"
                value={this.state.notes}
                id="notes"
                name="notes"
                onChange={this.handleChange}
                multiline
            />
            <FormLayout.Group>
                <TextField
                    label="Carriage"
                    value={this.state.carriage}
                    id="carriage"
                    name="carriage"
                    onChange={this.handleChange}
                    type="number"
                    prefix="£"
                />
                <TextField
                    label="Lead Time"
                    value={this.state.lead}
                    id="lead"
                    name="lead"
                    onChange={this.handleChange}
                    type="number"
                    suffix="Days"
                />
            </FormLayout.Group>
          </FormLayout>
      </Form>
    </Card>
  );
}
```

**Comment by BarryCarlyon** [comment] 2018-05-10 14:07
That results in:

![image](https://user-images.githubusercontent.com/20999/39873740-b2c351b4-5463-11e8-9a3d-05bdb6626390.png)

I'm currently doing

        return (
            <FormLayout>
                <Form onSubmit={this.handleSubmit}>
                    {formerror}
                    <FormLayout.Group>
                        <TextField
                            label="Supplier Name"
                            value={this.state.name}
                            id="name"
                            name="name"
                            onChange={this.handleChange}
                            error={this.checkError('name')}
                        />
                    </FormLayout.Group>

                    <FormLayout.Group>
                        <TextField
                            label="Notes"
                            value={this.state.notes}
                            id="notes"
                            name="notes"
                            onChange={this.handleChange}
                            multiline
                            helpText="This field expands on new lines! Write as much as you need!"
                        />
                    </FormLayout.Group>

                    <FormLayout.Group>
                        <TextField
                            label="Carriage"
                            value={this.state.carriage / 100}
                            id="carriage"
                            name="carriage"
                            onChange={this.handleChange}
                            type="number"
                            prefix="£"
                        />

                        <TextField
                            label="Lead Time"
                            value={this.state.leadtime}
                            id="leadtime"
                            name="leadtime"
                            onChange={this.handleChange}
                            type="number"
                            suffix="Days"
                            step="1"
                        />
                    </FormLayout.Group>

                    <Address
                        setAddress={this.setAddress}
                    />

                    <FormLayout.Group>
                        <Button
                            submit
                            primary
                            loading={this.state.loading}
                        >Create Supplier</Button>
                    </FormLayout.Group>
                </Form>
            </FormLayout>
        )

which results in a double gutter on the left

![image](https://user-images.githubusercontent.com/20999/39873805-d8f2372e-5463-11e8-87aa-bb3809f9bfaf.png)

**Comment by dfmcphee** [comment] 2018-05-10 14:17
Hey @BarryCarlyon, thanks for the issue. It looks like the problem here is that the `FormLayout.Group` has to be a direct child of the `FormLayout` because of how the margins work.

Using a structure like this:


```jsx
<Form>
  <Card title="Creating a new Supplier" sectioned>
    <FormLayout>
      <FormLayout.Group>
        <TextField
          label="Supplier Name"
          value="test"
          id="name"
          name="name"
        />
      </FormLayout.Group>

      <FormLayout.Group>
        <TextField
          label="Notes"
          value=""
          id="notes"
          name="notes"
          multiline
          helpText="This field expands on new lines! Write as much as you need!"
        />
      </FormLayout.Group>

      <FormLayout.Group>
        <TextField
          label="Carriage"
          value=""
          id="carriage"
          name="carriage"
          type="number"
          prefix="£"
        />

        <TextField
          label="Lead Time"
          value=""
          id="leadtime"
          name="leadtime"
          type="number"
          suffix="Days"
          step="1"
        />
      </FormLayout.Group>

      <FormLayout.Group>
        <Button submit primary>
          Create Supplier
        </Button>
      </FormLayout.Group>
    </FormLayout>
  </Card>
</Form>
```

Should give you this result:

<img width="972" alt="screen shot 2018-05-10 at 10 15 45 am" src="https://user-images.githubusercontent.com/478990/39874278-5bf5779a-543b-11e8-83ba-a03cb57c572a.png">

**Comment by dfmcphee** [comment] 2018-05-11 13:50
It looks like the HTML you have there has an extra `Polaris-FormLayout__Item` element that is causing that double margin. When I use the JSX example I gave above I get the following HTML.

```html
<form>
  <div class="Polaris-Card">
    <div class="Polaris-Card__Header">
      <h2 class="Polaris-Heading">Creating a new Supplier</h2>
    </div>
    <div class="Polaris-Card__Section">
      <div class="Polaris-FormLayout">
        <div role="group" class="">
          <div class="Polaris-FormLayout__Items">
            <div class="Polaris-FormLayout__Item">
              <div class="">
                <div class="Polaris-Labelled__LabelWrapper">
                  <div class="Polaris-Label"><label id="nameLabel" for="name" class="Polaris-Label__Text">Supplier Name</label></div>
                </div>
                <div class="Polaris-TextField Polaris-TextField--hasValue"><input name="name" id="name" class="Polaris-TextField__Input" aria-labelledby="nameLabel" aria-invalid="false" value="test">
                  <div class="Polaris-TextField__Backdrop"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div role="group" class="">
          <div class="Polaris-FormLayout__Items">
            <div class="Polaris-FormLayout__Item">
              <div class="">
                <div class="Polaris-Labelled__LabelWrapper">
                  <div class="Polaris-Label"><label id="notesLabel" for="notes" class="Polaris-Label__Text">Notes</label></div>
                </div>
                <div class="Polaris-TextField Polaris-TextField--multiline"><textarea name="notes" id="notes" class="Polaris-TextField__Input" aria-describedby="notesHelpText" aria-labelledby="notesLabel" aria-invalid="false"></textarea>
                  <div class="Polaris-TextField__Backdrop"></div>
                  <div aria-hidden="true" class="Polaris-TextField__Resizer">
                    <div class="Polaris-TextField__DummyInput"><br></div>
                    <div class="Polaris-TextField__DummyInput"><br></div>
                  </div>
                </div>
                <div class="Polaris-Labelled__HelpText" id="notesHelpText">This field expands on new lines! Write as much as you need!</div>
              </div>
            </div>
          </div>
        </div>
        <div role="group" class="">
          <div class="Polaris-FormLayout__Items">
            <div class="Polaris-FormLayout__Item">
              <div class="">
                <div class="Polaris-Labelled__LabelWrapper">
                  <div class="Polaris-Label"><label id="carriageLabel" for="carriage" class="Polaris-Label__Text">Carriage</label></div>
                </div>
                <div class="Polaris-TextField">
                  <div class="Polaris-TextField__Prefix" id="carriagePrefix">\xA3</div><input name="carriage" id="carriage" class="Polaris-TextField__Input" type="number" aria-labelledby="carriageLabel carriagePrefix" aria-invalid="false" value="">
                  <div class="Polaris-TextField__Spinner" aria-hidden="true">
                    <div role="button" class="Polaris-TextField__Segment" tabindex="-1">
                      <div class="Polaris-TextField__SpinnerIcon"><span class="Polaris-Icon"><svg class="Polaris-Icon__Svg" viewBox="0 0 20 20" focusable="false" aria-hidden="true"><path d="M15 12l-5-5-5 5z"></path></svg></span></div>
                    </div>
                    <div role="button" class="Polaris-TextField__Segment" tabindex="-1">
                      <div class="Polaris-TextField__SpinnerIcon"><span class="Polaris-Icon"><svg class="Polaris-Icon__Svg" viewBox="0 0 20 20" focusable="false" aria-hidden="true"><path d="M5 8l5 5 5-5z" fill-rule="evenodd"></path></svg></span></div>
                    </div>
                  </div>
                  <div class="Polaris-TextField__Backdrop"></div>
                </div>
              </div>
            </div>
            <div class="Polaris-FormLayout__Item">
              <div class="">
                <div class="Polaris-Labelled__LabelWrapper">
                  <div class="Polaris-Label"><label id="leadtimeLabel" for="leadtime" class="Polaris-Label__Text">Lead Time</label></div>
                </div>
                <div class="Polaris-TextField"><input name="leadtime" id="leadtime" class="Polaris-TextField__Input" type="number" aria-labelledby="leadtimeLabel leadtimeSuffix" aria-invalid="false" value="">
                  <div class="Polaris-TextField__Suffix" id="leadtimeSuffix">Days</div>
                  <div class="Polaris-TextField__Spinner" aria-hidden="true">
                    <div role="button" class="Polaris-TextField__Segment" tabindex="-1">
                      <div class="Polaris-TextField__SpinnerIcon"><span class="Polaris-Icon"><svg class="Polaris-Icon__Svg" viewBox="0 0 20 20" focusable="false" aria-hidden="true"><path d="M15 12l-5-5-5 5z"></path></svg></span></div>
                    </div>
                    <div role="button" class="Polaris-TextField__Segment" tabindex="-1">
                      <div class="Polaris-TextField__SpinnerIcon"><span class="Polaris-Icon"><svg class="Polaris-Icon__Svg" viewBox="0 0 20 20" focusable="false" aria-hidden="true"><path d="M5 8l5 5 5-5z" fill-rule="evenodd"></path></svg></span></div>
                    </div>
                  </div>
                  <div class="Polaris-TextField__Backdrop"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div role="group" class="">
          <div class="Polaris-FormLayout__Items">
            <div class="Polaris-FormLayout__Item"><button type="submit" class="Polaris-Button Polaris-Button--primary"><span class="Polaris-Button__Content"><span>Create Supplier</span></span></button></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>
```

Were you using that exact same code? Can you show what the full JSX you were using to generate that looks like?

**Comment by BarryCarlyon** [comment] 2018-05-11 13:51
It's in my original post on this thread…

**Comment by dfmcphee** [comment] 2018-05-11 13:53
Did you remove the extra `FormLayout` wrapping the `Form` from your original code? Here is a code sandbox with what I was suggesting.

https://codesandbox.io/s/ov72l54nmq

**Comment by BarryCarlyon** [comment] 2018-05-11 13:54
Yes

**Comment by BarryCarlyon** [comment] 2018-05-11 14:01
If I strip back my ENTIRE application to: 

https://gist.github.com/BarryCarlyon/64f69cd2791ade6aced79f94241d73c6

Which contains just your code

I get:

![image](https://user-images.githubusercontent.com/20999/39928047-27e5aafa-552c-11e8-836a-eb25e196f56c.png)

**Comment by BarryCarlyon** [comment] 2018-05-11 15:35
After doing a reinstall of all my deps cleanly one by one till the dev server came back up properly

![image](https://user-images.githubusercontent.com/20999/39932846-306fa4b6-5539-11e8-8e1e-d63680d22b70.png)

Double gutter on the left.

I'm about to try grabbing polaris from git and building that to see if for some reason it's NPM the problem in this ticket probably is the same problem as #318 

The JSX is right just something is throwing an extra element in somewhere for some reason. And it's getting to the hair tearing out point now

**Comment by BarryCarlyon** [comment] 2018-05-11 15:40
Literally no idea what the swear word is going on now:

Comparing react tree's using chrome react plugin

![image](https://user-images.githubusercontent.com/20999/39933125-032a1a94-553a-11e8-99da-c9f7728e4f1f.png)

**Comment by BarryCarlyon** [comment] 2018-05-14 10:04
This bug is making it a nightmare to develop with Polaris right now.

Things keep getting wrapped in other things for no reason…

**Comment by dfmcphee** [comment] 2018-05-15 13:52
Hey @BarryCarlyon. I have been trying to reproduce your issue but have not had luck. Is it possible to share your full app setup in a repo somewhere so we can take a closer look?

Alternatively, I just tried a fresh copy of [shopify-node-app](https://github.com/Shopify/shopify-node-app) with the code above and it worked fine. You could use that project as a starting point because it has a similar setup to what you are using (react, node, express).

**Comment by BarryCarlyon** [comment] 2018-05-15 13:55
My app/project is based off the back of shopify-node-app

Did you run as `npm run dev` the problem only exists when running as dev with hotreload enabled.

If I run build and then `npm run prod` (same as shopify-node-app) the issue is not present

**Comment by dfmcphee** [comment] 2018-05-15 14:37
Just tried again and it worked for me with `npm run dev` as well. I noticed though that our `react-hot-loader` packages were different versions though and when I updated to `4.0.0` like you have in your package, I am now seeing the same issue.

For now I would suggest rolling back to version `3.1.3` of `react-hot-loader` and I will create an issue to get this fixed in `react-utilities` to support version 4+.

**Comment by BarryCarlyon** [comment] 2018-05-15 14:39
My gist posted four days ago included my package.json …

I'll roll back and retest

**Comment by BarryCarlyon** [comment] 2018-05-15 14:45
Rolling back to `3.1.3` of `react-hot-loader` fixes this and #318

**Comment by ry5n** [comment] 2018-06-07 00:59
We have a potential fix for this that we’re testing internally.

**Closed** 2018-08-17 21:35 UTC
Labels: fix in progress

**Comment by ry5n** [comment] 2018-08-17 21:42
We’ve got a fix for this that will be available in the next release. Thanks for your patience 💜

**Comment by delyan-peev** [comment] 2021-11-08 07:38
Still not fixed

**Comment by boost-shop** [comment] 2023-06-14 03:15
Still not fixed
