### ISSUE TITLE
Checkbox: ID ambiguity

### ISSUE THREAD

**Issue by sp4cecat** [Shopify/polaris#194] opened 2017-10-09 04:44 UTC
# Issue summary

If a checkbox 'id' attribute is the same across multiple components, clicking any of those checkboxes only triggers a response on the first checkbox, as they all share the same "id" Polaris form elements send id instead of the 'name' attribute. This behaviour occurs at the DOM level, of course.

## Expected behavior

label 'for' attribute should be different for each element affected, or simply omitted.

## Actual behavior

As each label surrounding each checkbox has the same 'for' value, so only first checkbox is triggered.

## Steps to Reproduce the Problem

1. Create a component that renders a form section, passing section-specific values and a unique identifier. Pass a change handler that accepts a key, value and the unique identifier
  eg: 
    ```jsx
    <FormBit
       data={ "flag": 1, "isSelected": 0, uniqueId": 6} 
       handleChange={this.handleChange}
    </FormBit>
    ```
1. Handle changing within the element, pass updates to the parent handler function
  `props.handleChange( k, v, identifier )`
1. State at top level is stored as
  `{ fieldName: [{identifier: value}, {identifier: value} ... ] }`

## Specifications

- Polaris version: 1.6
- React version: 16
- Browser: Chrome 
- Device: iMac
- Operating System: OSX High Sierra

**Comment by dleroux** [comment] 2017-10-26 19:08
@sp4cecat can you clarify what your issue is. If you pass an `id` prop to the Checkbox it will be used, but if you don't a unique Id will be generated for each and used by the label `for` attribute.

**Comment by sp4cecat** [comment] 2017-10-27 00:30
So, you've got multiple form subcomponents, each with their own change handler and state, and they each have a checkbox with the same id - 'willAttend' for example.

However, when rendered to the DOM, only the first checkbox gets triggered.

**Comment by chloerice** [comment] 2017-10-27 14:40
Can you share the full code that you're using the Checkbox component in? It will be difficult to see where the problem lies without it.

**Comment by sp4cecat** [comment] 2017-11-23 07:48
I've written around the issue so I don't have the original code to show, but hopefully this demonstrates.

The parent app loops through the items and renders three subcomponents, each with a checkbox with an id of "inStock" As the Polaris change handler uses the "id" field instead of the "name" field, the option of leaving the ID blank is pretty .. uworkable.

```
class App extends React.Component {

  constructor(props)
  {
    super(props)
    this.state =
      {
      shoes: {
        "1": {color: "Green", inStock: true},
        "2": {color: "Blue", inStock: true},
        "3": {color: "Red", inStock: true}
      }
    }
  }

  handleChange = (id, key, val) => {

    let shoes = this.state.shoes

    shoes[id][key] = val

    this.setState({shoes: shoes})

  }

  render() {

    return (

      <Page title="Shoes!">
        <Layout>
          <Layout.AnnotatedSection
            title="Edit Shoes"
            >
            <Card sectioned>
              {Object.keys(this.state.shoes).map( (id) => {
                return (
                  <SeeShoe
                    id={id}
                    shoe={this.state.shoes.id}
                    handleChange={this.handleChange}
                    />
                )
              })}
            </Card>
          </Layout.AnnotatedSection>
        </Layout>
      </Page>
    )

  }
}

class SeeShoe extends React.Component {

  handleChange = (v, k) => {
    this.props.handleChange( this.props.id, k, v)
  }

  render() {

    const props = this.props

    return "(
    <FormLayout.Group>
      <TextField
        type="text"
        label="Color"
        id="color"
        name="color"
        onChange={this.handleChange}
        value={props.shoe.color}
        />
      <Checkbox
        label="in Stock?"
        checked={props.shoe.inStock}
        onChange={this.handleChange}
        id="inStock"
        name="inStock"
        />
      </FormLayout.Group>
      )"

  }

}
```

**Comment by chloerice** [comment] 2017-11-23 20:22
Hi @sp4cecat, without being able to see and run the actual code causing the problem we can't help you pinpoint the error in your app. But I do see some issues with the example code above that I hope will help you. It seems to be a programmatic issue with your handleChange, not an HTML issue where the `id` is concerned.

- The value being passed to SeeShoe's `shoe` prop is trying to access each shoe's value with an `id` key that doesn't exist on the `shoes` object. I think you mean to use the id argument from your map callback like `this.state.shoes[id]` instead of `this.state.shoes.id` (which throws a reference error as it's undefined).

- [React nodes mapped from an array should be given keys](https://reactjs.org/docs/lists-and-keys.html)

- [State should be treated as if it were immutable](https://reactjs.org/docs/state-and-lifecycle.html#using-state-correctly) (not able to be changed manually). This may or may not be part of the problem you're having, but it has side effects that can make errors hard to trace especially if your state grows to include other things. I'd recommend unnesting the things you need to handle the change of. That said, each form should have its own state. SeeShoe is already a class, so if you handle the changes of the form internally, you can pass the updated shoe itself to the App's handle change so that App and its children stay in sync.

<details>
<summary>Click to see collapsed example code refactored with the above in mind.</summary>

```jsx
class App extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
      shoes: {
        1: {color: "Green", inStock: true},
        2: {color: "Blue", inStock: true},
        3: {color: "Red", inStock: true}
      }
    }
  }

  handleChange = (id) => (shoe) => {
    // copy state values so state isn't mutated directly
    const nextState = {...this.state.shoes}
    nextState[id] = shoe
    this.setState({shoes: nextState})
  }

  render() {
    return (
      <Page title="Shoes!">
        <Layout>
          <Layout.AnnotatedSection title="Edit Shoes">
            <Card sectioned>
              {
                Object.keys(shoes).map((id) => (
                  <SeeShoe
                    key={id}
                    shoe={this.state.shoes[id]}
                    handleChange={this.handleChange(id)}
                  />
                ))
              }
            </Card>
          </Layout.AnnotatedSection>
        </Layout>
      </Page>
    )
  }
}

class SeeShoe extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
      color: '',
      inStock: true
    }
  }
  // instead of using the corresponding shoe object's keys as `id` in your form fields,
  // use closure to pass in the key for use in setting state
  handleChange = (key) => (value) => {
    // copy state values so state isn't mutated directly
    const shoe = {...this.state}
    shoe[key] = value
    this.setState(
      {[key]: value},
      // setState takes a callback as its optional second parameter
      ( ) => { this.props.handleChange(shoe) }
    )
  }

  render( ) {
    return (
      <FormLayout>
        <TextField
          type="text"
          label="Color"
          id={`shoe-${this.props.shoe.id}-color`}
          name="color"
          onChange={this.handleChange('color')}
          value={this.state.color}
        />
        <Checkbox
          label="In Stock"
          checked={this.state.inStock}
          onChange={this.handleChange('inStock')}
          id={`shoe-${this.props.shoe.id}`} // HTML `id` must be unique
          name="inStock"
        />
      </FormLayout>
    )
  }
}
```  

</details>

**Comment by sp4cecat** [comment] 2017-11-24 02:43
I should really have mentioned that the code was just for illustrative purposes only - I just made it up and didn't test it at all.

The issue comes down to this:

- Polaris uses the id parameter when handling updates, not the name parameter
- When you add an ID to a checkbox component (as you must) it uses that ID in the 'for' attribute of the label
- If there are multiples of a checkbox with the same id/name on the same page, they will ALL have the same 'for' parameter in the encompassing label, and clicking on ANY of them will select the FIRST INSTANCE

Hope that helps :)

Paul

**Comment by ry5n** [comment] 2018-03-13 02:07
In plain HTML, each checkbox must have a unique id—multiple checkboxes with the same id will be invalid markup. If you have multiple labels associated with a single checkbox using the `for` attribute, they will all toggle that checkbox, which is expected behavior for HTML.

Given those constraints, I think the described behavior is what’s expected even outside of Polaris. I’m not 100% sure I understand though, so let me know if I’ve missed something.

**Closed by ry5n** 2018-03-13 02:07 UTC
