### ISSUE TITLE
ResourcePicker's onClose and onSelection callbacks never called

### ISSUE THREAD

**Issue by tophattom** [Shopify/polaris#148] opened 2017-07-25 10:12 UTC
# Issue summary

With the example code from https://polaris.shopify.com/components/embedded/resource-picker#examples it seems that the `onClose` and `onSelection` callbacks don't seem to fire. The modal does close but the enclosing component's state is not modified and nothing is logged to console.

## Expected behavior

Enclosing component's state should have `open: false` after closing the modal. Selected products should be logged to console.

## Actual behavior

State remains `open: true` event though the modal closes. Nothing is logged to console.

## Specifications

- Polaris version: 1.1.1
- React version: 15.6.1
- Browser: Chrome 59.0.3071.115
- Operating System: OS X 10.11.6

**NOTE:** This repo is only used for reporting issues and new feature requests. We are not accepting pull requests at this point in time.

**Comment by lemonmade** [comment] 2017-07-25 14:01
Hey @tophattom, can you please post the code you are using that is exhibiting this issue?

**Comment by tophattom** [comment] 2017-07-26 06:58
Here's a minimal example which reproduces this problem.
```jsx
export default class App extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      open: false
    };
  }

  render() {
    return (
      <EmbeddedApp
        shopOrigin={shopOrigin}
        apiKey={apiKey}
        forceRedirect={true}>

        <div>
          <Button onClick={() => { this.setState({ open: true }) }}>Select products</Button>
          <ResourcePicker
              products
              open={this.state.open}
              onSelection={(resources) => {
                console.log('Selected products: ', resources.products);
                this.setState({open: false});
              }}
              onCancel={() => this.setState({open: false})}
            />
        </div>
      </EmbeddedApp>
    );
  }
}
```

**Comment by tophattom** [comment] 2017-07-31 08:09
Any update on this?

**Comment by tmlayton** [comment] 2017-10-03 03:24
Hi @tophattom, I'm taking a look at this issue but currently unable to reproduce with the code snippet you provided. We are tracking internally and will post back here with an update.

**Comment by tmlayton** [comment] 2017-10-03 18:26
Hi @tophattom, does your `shopOrigin` string contain a trailing slash?

**Comment by tophattom** [comment] 2017-10-04 08:48
No, it doesn't. However I am not able to reproduce this at the moment for some reason. 🤔

**Comment by tmlayton** [comment] 2017-10-04 19:37
Okay, thanks for the response. I'm going to close this issue for now. If you run into a similar issue in the future, check that your `shopOrigin` matches exactly (e.g. no trailing slashes, etc) otherwise the post message from Shopify to your app, which triggers the callback, will be rejected.

**Closed by tmlayton** 2017-10-04 19:37 UTC
Labels: fix in progress
