### ISSUE TITLE
Use proper cursor for disabled elements

### ISSUE THREAD

**Issue by bakura10** [Shopify/polaris#138] opened 2017-07-18 14:11 UTC
# Issue summary

When a button is disabled, it does not use the correct cursor.

## Expected behavior

Disabled button should have the cursor: not-allowed CSS rule.

## Actual behavior

Disabled button are using the standard cursor which does not bring the correct information to the user.

## Specifications

- Polaris version: 1.1.1
- React version: 15.16
- Browser: Chrome
- Operating System: OS X Sierra

**Comment by ry5n** [comment] 2017-07-18 20:52
Thanks @bakura10. 

This is related to #132. We’re currently reflecting the browser default cursor for disabled buttons, so this isn’t necessarily a bug. We’re going to take a look at this and decide on a holistic strategy for cursor styling, so I’m going to consider this a duplicate of #132. I’ll report back in that issue when I have more info.

For now, I would recommend _not_ changing this as an override in your apps, to ensure merchants have a consistent experience with using interfaces built with Polaris.

**Closed by ry5n** 2017-07-18 20:52 UTC

**Comment by ry5n** [comment] 2017-10-26 15:35
To conclude this, we’re planning to keep the existing styling. So cursor: pointer will be used for buttons, but others left with their browser defaults.
