### ISSUE TITLE
Add date picker to filter

### ISSUE THREAD

**Issue by zheren2018** [Shopify/polaris#405] opened 2018-08-20 02:50 UTC
Add date picker to filter

Add date picker to filter, just like this
![image](https://user-images.githubusercontent.com/39551669/44318019-aa904080-a466-11e8-8a44-cf8e94f6601f.png)

## Rationale

Users can change the data range easily 
---

⚓️ We’re not accepting pull requests at this time<br />
🗒 We _are_ accepting issue reports and feature requests<br />
🌟 Feature requests that we can’t get to right away will be closed. However, we track all requests and will use it to set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by tmlayton** [comment] 2018-08-20 15:51
@zheren2018 thanks for the issue. This is a duplicate of #377, please upvote (👍) on the description in #377 instead.

**Closed by tmlayton** 2018-08-20 15:51 UTC
