### ISSUE TITLE
Embedded SDK breadcrumb navigation broken?

### ISSUE THREAD

**Issue by twinkelm** [Shopify/polaris#333] opened 2018-05-30 20:07 UTC
Hello,

I cannot get the breadcrumb navigation of the embedded sdk working consistently. It seems to be broken with both the standalone as well as the react version. 

Very simple standalone prototype with 2 pages.

Page 1:
```
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://sdks.shopifycdn.com/polaris/latest/polaris.css" />
    <script src="https://cdn.shopify.com/s/assets/external/app.js"></script>
    <script type="text/javascript">
      ShopifyApp.init({
        apiKey: 'xxxx',
        shopOrigin: 'https://xxx.myshopify.com'
      });
    </script>
  </head>
  <body>
    <script type="text/javascript">
      ShopifyApp.ready(function(){
        ShopifyApp.Bar.initialize({
          title: 'Index'
        });
      });
    </script>
    <h1> index page </h1>
    <a href="stammdaten.html">Stammdaten</a>
  </body>
</html>
```

Page 2:
```
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://sdks.shopifycdn.com/polaris/latest/polaris.css" />
    <script src="https://cdn.shopify.com/s/assets/external/app.js"></script>
    <script type="text/javascript">
      ShopifyApp.init({
        apiKey: 'xxx',
        shopOrigin: 'https://xxx.myshopify.com'
      });
    </script>
  </head>
  <body>
    <script type="text/javascript">
      ShopifyApp.ready(function(){
        ShopifyApp.Bar.initialize({
          title: 'Stammdaten',
          buttons: {
            primary: {
              label: 'Save',
              message: 'save',
              callback: function(){
                alert('hi stammdaten');
              }
            }
          }
        });
      });
    </script>
    <h1> stammdaten page </h1>
    <a href="index.html">Index</a>
  </body>
</html>
```

## Expected behavior

1. When navigating from the index page of the embedded app to the stammdaten page by using the a href link the index.html page, a breadcrumb element 'Stammdaten' gets added, thats fine.
2. Clicking the name of the app in the Shopify App Bar to navigate should bring be back to the index page of the embedded app.

![image](https://user-images.githubusercontent.com/411103/40744517-1142987a-6455-11e8-8c83-0be6951563c0.png)

## Actual behavior

1. When navigating from the index page of the embedded app to the stammdaten page by using the a href link the index.html page, a breadcrumb element 'Stammdaten' gets added, thats fine.
2. When clicking on the name of the app in the Shopify App Bar to navigate back, this is actually ignored in the embedded iframe, and the embedded app does not navigate back to its homepage.

## Steps to reproduce the problem

1. create an app with two static pages as per samples above
2. navigate between the pages, using both the embedded links in the app as well as the Shopify Bar Breadcrumbs to navigate

## Specifications

- Polaris version: latest from CDN
- React version: ./.
- Browser: Chrome V66, Safari 11.1
- Device: Laptop
- Operating System: MacOS

---

⚓️ We’re not accepting pull requests at this time<br />
🗒 This repo is for reporting issues and feature requests only

**Comment by twinkelm** [comment] 2018-06-04 08:06
Thank you very much @tmlayton for confirming. 
Is there any ETA for the fix, if I may ask? 
Thanks a lot!

**Comment by tmlayton** [comment] 2018-06-04 16:29
You‘re welcome! I just merged the fix a few seconds ago – it will be deployed shortly.

**Comment by rnovacek** [comment] 2018-06-11 10:15
First breadcrumb (if there are more than one) still doesn't work properly in our app. Was the fix deployed already?

I just see this message in the console but nothing happens:
```
[iframe Messenger]: Received message: {"message":"Shopify.API.setWindowLocation","data":"<app url>"} from https://<shop-domain>.myshopify.com
```

This is quite serious issue for us and it breaks navigation in the app and user have to refresh the app completely to get back to app home page. Is there any known workaround?

**Comment by tmlayton** [comment] 2018-06-11 17:38
@rnovacek 👋 apologizes, I should have left the issue open and clarified there is a temporary workaround with the fixed we deployed to Shopify. The workaround is to [include the Embedded App SDK JavaScript](https://help.shopify.com/api/embedded-apps/embedded-app-sdk/initialization):

```html
<head>
  <script src="https://cdn.shopify.com/s/assets/external/app.js"></script>
  <script type="text/javascript">
    ShopifyApp.init({
      apiKey: 'YOUR_APP_API_KEY',
      shopOrigin: 'https://CURRENT_LOGGED_IN_SHOP.myshopify.com'
    });
  </script>
  ...
</head>
```

We are working on a fix for this now and tracking internally.

**Closed** 2018-06-11 23:14 UTC
Labels: fix in progress

**Comment by tmlayton** [comment] 2018-06-11 23:21
The fix has merged and we will do a patch release tomorrow.

**Comment by tmlayton** [comment] 2018-06-12 19:45
https://github.com/Shopify/polaris/releases/tag/v2.2.0

**Comment by kusaeva** [comment] 2018-06-14 17:50
Just updated to v2.2.0

When I click on the app name in the embedded app bar:
<img width="556" alt="screen shot 2018-06-14 at 20 46 18" src="https://user-images.githubusercontent.com/5486933/41428982-5f81a042-7014-11e8-8431-976463b62984.png">

I got an empty iframe and this message in the console

> Refused to display 'https://splash-test-store.myshopify.com/admin/apps/whimm' in a frame because it set 'X-Frame-Options' to 'deny'.

Is there something I can do to fix it?

**Comment by tmlayton** [comment] 2018-06-15 22:00
Are you initializing the embedded app SDK via the `AppProvider`?

```js
<AppProvider
  apiKey="YOUR_APP_API_KEY"
  shopOrigin="https://CURRENT_LOGGED_IN_SHOP.myshopify.com"
>
  <MyApp />
</AppProvider>
```

**Comment by kusaeva** [comment] 2018-06-16 07:36
Yes, exactly. Maybe the problem is in my implementation: I authorize user at backend and then redirect to app url. It's ok on first launch, but when breadcrumb navigation is used, i suppose all of that takes place in iframe and i got an error. Don't know how to fix it...
Anyway, thank you

**Comment by pRoy24** [comment] 2019-02-10 17:28
Hitting the same issue, where I am authorizing user at backend and rendering app from backend endpoint.. problem is I am unable to redirect user from within the app to admin

**Comment by pRoy24** [comment] 2019-02-10 18:14
> Hitting the same issue, where I am authorizing user at backend and rendering app from backend endpoint.. problem is I am unable to redirect user from within the app to admin

nvm Found the solution ..for anyone hitting the same issue, in order to navigate to an admin path you need to specify target: 'ADMIN_PATH' in the breadcrumb definition.
