### ISSUE TITLE
ResourceList with sortOptions broken styles

### ISSUE THREAD

**Issue by janklimo** [Shopify/polaris#355] opened 2018-06-11 04:05 UTC
# Issue summary

`ResourceList` with `sortOptions` doesn't render correctly:

![screen shot 2018-06-11 at 11 01 03 am](https://user-images.githubusercontent.com/7811733/41212280-f43cc9f6-6d66-11e8-832a-6a1863e7999d.png)

## Expected behavior

The sort toolbar should show above the list.

## Specifications

- Polaris version: `2.1.2`
- React version: `16.3.2`
- Browser: Chrome
- Operating System: OS X El Capitan

**Comment by ry5n** [comment] 2018-06-11 15:12
Thanks for reporting this @janklimo. I can reproduce the bug and I’ve filed an issue on our internal tracker to get it fixed.

**Comment by dleroux** [comment] 2018-06-26 12:30
I'm going close this since a fix will be becoming in the next release. Again thanks for reporting this @janklimo.

**Closed by dleroux** 2018-06-26 12:30 UTC

**Comment by ry5n** [comment] 2018-07-04 00:03
A fix for this was released this morning in [2.3.0](https://github.com/Shopify/polaris/releases/tag/v2.3.0)
