### ISSUE TITLE
Feature request: Support multiple flash error messages

### ISSUE THREAD

**Issue by macs91** [Shopify/polaris#115] opened 2017-07-01 11:08 UTC
# Issue summary

The flash method API does not allow to display more than one error at the same time.

## Actual behaviour
Every subsequent call of the `flashError` method removes the previous error.

## Expected behaviour
Subsequent calls of `flashError` display errors on top of each other (see Blueprint [Toast](http://blueprintjs.com/docs/#core/components/toast) component behaviour).

**Comment by ry5n** [comment] 2017-07-14 23:55
Thanks for the request. In Shopify admin we tend to avoid showing more than one flash message at a time and prefer other strategies for multi-error scenarios. One of them might be a good fit—can you describe your particular case?

**Comment by macs91** [comment] 2017-07-15 09:55
The scenario is an advanced ERP connector with back-office features that allows the user to run background operations (e.g. manually request a stock update, import new products from the ERP, etc). The app is made of different screens (pages) so the user could be in a different page from the one where he previously started the operation. Since multiple operations can be started, it could happen that they fail at a time close to each other, hence I cannot use flash error messages otherwise one error would overwrite the other.

**Comment by ry5n** [comment] 2017-07-17 18:18
Ah, I see. The issue is that since Flash messages aren’t actionable, they’re not great for helping the merchant to get back to where they were, and to resolve the problem (they work best as confirmation of successful actions, rather than errors). Unfortunately I don’t think we have a better option currently in the EASDK.

Since this can’t be addressed in the Polaris components directly, I’m going to close this. But I have logged this as a requested enhancement in the EADSK implementation. We’ll look into it.

**Closed by ry5n** 2017-07-17 18:18 UTC
